CW18_1/Models/Address.cs
using System.ComponentModel.DataAnnotations;

namespace CW18_1.Models
{
    public class Address
    {
        //public int Id { get; set; }
        public string Addresss { get; set; }

        [Key]
        public int MemberId { get; set; }
        public Member Member { get; set; }
        public City City { get; set; }
        public int CityId { get; set; }
    }
}

CW18_1/Models/Book.cs
namespace CW18_1.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public ICollection<Member> Members { get; set; }
        public int ZhanrId { get; set; }
        public Zhanr zhanr { get; set; }
    }
}

CW18_1/Models/City.cs
using System.ComponentModel.DataAnnotations;

namespace CW18_1.Models
{
    public class City
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public List<Address> Addresses { get; set; }
        public int StateId { get; set; }
        public State State { get; set; }
    }
}

CW18_1/Models/Dtos/BorrowedBooksByStateDto.cs
namespace CW18_1.Models.Dtos
{
    public class BorrowedBooksByStateDto
    {
        public string StateName { get; set; }
        public List<string> ListOfBookTitles { get; set; }
    }
}

CW18_1/Models/Dtos/MemberGroupByStateDto.cs
namespace CW18_1.Models.Dtos
{
    public class MemberGroupByStateDto
    {
        public string StateName { get; set; }
        public List<Member> Members { get; set; }
    }
}

CW18_1/Models/ErrorViewModel.cs
namespace CW18_1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CW18_1/Models/Member.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace CW18_1.Models
{
    public class Member
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public ICollection<Book> Books { get; set; }
        public Address Address { get; set; }
    }
}

CW18_1/Models/State.cs
namespace CW18_1.Models
{
    public class State
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<City> Cities { get; set; }
    }
}

CW18_1/Models/Zhanr.cs
namespace CW18_1.Models
{
    public class Zhanr
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public List<Book> Books { get; set; }
    }
}

CW18_1/Controllers/HomeController.cs
using CW18_1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CW18_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CW18_1/Controllers/LibraryController.cs
using CW18_1.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CW18_1.Controllers
{
    public class LibraryController : Controller
    {
        private readonly ILibraryRepository _libraryRepository;

        public LibraryController(ILibraryRepository libraryRepository)
        {
            _libraryRepository = libraryRepository;
        }


        public IActionResult DisplayMembers()
        {
            var MembersByState = _libraryRepository.GetAllMemberGroupByState();

            return View(MembersByState);
        }

        public IActionResult DisplayBorrowedBooksByMember()
        {
           var members = _libraryRepository.GetAllBooksBorrowedByMember();
            return View(members);
        }

        public IActionResult GetBooksGroupByStates()
        {
            return View(_libraryRepository.GetBorrowedBooksGroupByState());
        }
    }
}

CW18_1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CW18_1/Views/Library/DisplayBorrowedBooksByMember.cshtml
@model List<CW18_1.Models.Member>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>اسم کاربر</th>
            <th>اسامی کتابها</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FirstName @item.LastName</td>
                <td>
                    <ul>
                        @foreach (var book in item.Books)
                        {
                            <li>@book.Title @book.zhanr</li>

                        }
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>

CW18_1/Views/Library/DisplayMembers.cshtml
@model List<CW18_1.Models.Dtos.MemberGroupByStateDto>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>اسم استان</th>
            <th>اسامی کاربران</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.StateName</td>
                <td>
                    <ul>
                        @foreach (var member in item.Members)
                        {
                            <li>@member.FirstName @member.LastName</li>

                        }
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>

CW18_1/Views/Library/GetBooksGroupByStates.cshtml
@model List<CW18_1.Models.Dtos.BorrowedBooksByStateDto>
<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>اسم استان</th>
            <th>اسامی کتابها</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.StateName</td>
                <td>
                    <ul>
                        @foreach (var book in item.ListOfBookTitles)
                        {
                            <li>@book</li>
                        }
                    </ul>
                </td>
            </tr>
        }
    </tbody>
</table>

CW18_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CW18_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CW18_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CW18_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="DisplayMembers">نمایش اعضا به تفکیک استان</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="DisplayBorrowedBooksByMember">نمایش کتابها به تفکیک  اعضا</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="GetBooksGroupByStates">نمایش کتابهای قرض گرفته شده به تفکیک استان</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CW18_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>